const express = require('express');
const router = express.Router();
const axios = require('axios');
const multer = require('multer');
const FormData = require('form-data');
const fs = require('fs');
const path = require('path');

// Ensure uploads directory exists
const uploadDir = path.join(__dirname, '../uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

const upload = multer({ dest: 'uploads/' });

router.post('/', upload.single('image'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ message: 'No image provided' });

    const formData = new FormData();
    formData.append('media', fs.createReadStream(req.file.path));
    formData.append('models', 'genai');
    formData.append('api_user', process.env.SIGHTENGINE_API_USER);
    formData.append('api_secret', process.env.SIGHTENGINE_API_SECRET);

    const sightengineResponse = await axios.post('https://api.sightengine.com/1.0/check.json', formData, {
      headers: formData.getHeaders()
    });

    // Cleanup the uploaded file
    fs.unlinkSync(req.file.path);

    const result = sightengineResponse.data;
    if (result.status === 'success') {
      // Sightengine "genai" model returns probability score
      // result.type.ai_generated 
      const fakeScore = result.type && result.type.ai_generated ? result.type.ai_generated * 100 : 0;
      const fakePct = Math.round(fakeScore);
      const realPct = 100 - fakePct;

      res.json({
        verdict: fakePct > 50 ? 'AI-GENERATED / DEEPFAKE' : 'REAL IMAGE',
        confidence: Math.max(fakePct, realPct),
        explanation: `Sightengine detection determined there is a ${fakePct}% chance this image is generated by AI and a ${realPct}% chance it is real.`
      });
    } else {
      res.status(500).json({ message: 'Sightengine API error', details: result });
    }
  } catch (err) {
    console.error('Deepfake API Error:', err.message);
    if (req.file && fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
    res.status(500).json({ message: 'Server error during deepfake detection' });
  }
});

module.exports = router;
